"""Points of interest that receive storm-arrival countdowns.

type: city | airport | agri (rural block / district HQ representing farming communities)
"""
PLACES = [
    # West Bengal
    {"id": "kolkata", "name": "Kolkata", "state": "WB", "lat": 22.572, "lon": 88.364, "type": "city"},
    {"id": "howrah", "name": "Howrah", "state": "WB", "lat": 22.595, "lon": 88.263, "type": "city"},
    {"id": "VECC", "name": "Kolkata Airport (CCU)", "state": "WB", "lat": 22.654, "lon": 88.447, "type": "airport"},
    {"id": "durgapur", "name": "Durgapur", "state": "WB", "lat": 23.520, "lon": 87.312, "type": "city"},
    {"id": "asansol", "name": "Asansol", "state": "WB", "lat": 23.683, "lon": 86.983, "type": "city"},
    {"id": "bardhaman", "name": "Bardhaman", "state": "WB", "lat": 23.233, "lon": 87.861, "type": "agri"},
    {"id": "bankura", "name": "Bankura", "state": "WB", "lat": 23.232, "lon": 87.070, "type": "agri"},
    {"id": "midnapore", "name": "Medinipur", "state": "WB", "lat": 22.424, "lon": 87.319, "type": "agri"},
    {"id": "kharagpur", "name": "Kharagpur", "state": "WB", "lat": 22.346, "lon": 87.232, "type": "city"},
    {"id": "haldia", "name": "Haldia", "state": "WB", "lat": 22.060, "lon": 88.110, "type": "city"},
    {"id": "krishnanagar", "name": "Krishnanagar", "state": "WB", "lat": 23.405, "lon": 88.490, "type": "agri"},
    {"id": "malda", "name": "Malda", "state": "WB", "lat": 25.011, "lon": 88.141, "type": "agri"},
    {"id": "siliguri", "name": "Siliguri", "state": "WB", "lat": 26.727, "lon": 88.395, "type": "city"},
    {"id": "VEBD", "name": "Bagdogra Airport (IXB)", "state": "WB", "lat": 26.681, "lon": 88.328, "type": "airport"},
    {"id": "coochbehar", "name": "Cooch Behar", "state": "WB", "lat": 26.324, "lon": 89.451, "type": "agri"},
    # Jharkhand
    {"id": "ranchi", "name": "Ranchi", "state": "JH", "lat": 23.344, "lon": 85.310, "type": "city"},
    {"id": "VERC", "name": "Ranchi Airport (IXR)", "state": "JH", "lat": 23.314, "lon": 85.321, "type": "airport"},
    {"id": "jamshedpur", "name": "Jamshedpur", "state": "JH", "lat": 22.805, "lon": 86.203, "type": "city"},
    {"id": "dhanbad", "name": "Dhanbad", "state": "JH", "lat": 23.796, "lon": 86.430, "type": "city"},
    {"id": "bokaro", "name": "Bokaro", "state": "JH", "lat": 23.669, "lon": 86.151, "type": "city"},
    {"id": "hazaribagh", "name": "Hazaribagh", "state": "JH", "lat": 23.992, "lon": 85.361, "type": "agri"},
    {"id": "gumla", "name": "Gumla", "state": "JH", "lat": 23.044, "lon": 84.542, "type": "agri"},
    # Bihar
    {"id": "patna", "name": "Patna", "state": "BR", "lat": 25.594, "lon": 85.138, "type": "city"},
    {"id": "VEPT", "name": "Patna Airport (PAT)", "state": "BR", "lat": 25.591, "lon": 85.088, "type": "airport"},
    {"id": "gaya", "name": "Gaya", "state": "BR", "lat": 24.796, "lon": 85.008, "type": "city"},
    {"id": "muzaffarpur", "name": "Muzaffarpur", "state": "BR", "lat": 26.120, "lon": 85.391, "type": "agri"},
    {"id": "bhagalpur", "name": "Bhagalpur", "state": "BR", "lat": 25.244, "lon": 86.972, "type": "city"},
    {"id": "darbhanga", "name": "Darbhanga", "state": "BR", "lat": 26.152, "lon": 85.897, "type": "agri"},
    {"id": "purnia", "name": "Purnia", "state": "BR", "lat": 25.778, "lon": 87.475, "type": "agri"},
    {"id": "chapra", "name": "Chhapra", "state": "BR", "lat": 25.780, "lon": 84.730, "type": "agri"},
    # Odisha
    {"id": "bhubaneswar", "name": "Bhubaneswar", "state": "OD", "lat": 20.296, "lon": 85.825, "type": "city"},
    {"id": "VEBS", "name": "Bhubaneswar Airport (BBI)", "state": "OD", "lat": 20.244, "lon": 85.818, "type": "airport"},
    {"id": "cuttack", "name": "Cuttack", "state": "OD", "lat": 20.463, "lon": 85.883, "type": "city"},
    {"id": "balasore", "name": "Balasore", "state": "OD", "lat": 21.494, "lon": 86.933, "type": "city"},
    {"id": "angul", "name": "Angul", "state": "OD", "lat": 20.840, "lon": 85.102, "type": "agri"},
    {"id": "dhenkanal", "name": "Dhenkanal", "state": "OD", "lat": 20.658, "lon": 85.596, "type": "agri"},
    {"id": "keonjhar", "name": "Keonjhar", "state": "OD", "lat": 21.629, "lon": 85.582, "type": "agri"},
    {"id": "rourkela", "name": "Rourkela", "state": "OD", "lat": 22.260, "lon": 84.854, "type": "city"},
    {"id": "sambalpur", "name": "Sambalpur", "state": "OD", "lat": 21.466, "lon": 83.982, "type": "agri"},
    # North-East
    {"id": "guwahati", "name": "Guwahati", "state": "AS", "lat": 26.144, "lon": 91.736, "type": "city"},
    {"id": "VEGT", "name": "Guwahati Airport (GAU)", "state": "AS", "lat": 26.106, "lon": 91.586, "type": "airport"},
    {"id": "shillong", "name": "Shillong", "state": "ML", "lat": 25.578, "lon": 91.893, "type": "city"},
    {"id": "sohra", "name": "Sohra (Cherrapunji)", "state": "ML", "lat": 25.271, "lon": 91.732, "type": "agri"},
    {"id": "agartala", "name": "Agartala", "state": "TR", "lat": 23.831, "lon": 91.286, "type": "city"},
    {"id": "VEAT", "name": "Agartala Airport (IXA)", "state": "TR", "lat": 23.887, "lon": 91.241, "type": "airport"},
    # Other regions (used when NOWCAST_REGION selects them)
    {"id": "delhi", "name": "New Delhi", "state": "DL", "lat": 28.614, "lon": 77.209, "type": "city"},
    {"id": "VIDP", "name": "Delhi Airport (DEL)", "state": "DL", "lat": 28.556, "lon": 77.100, "type": "airport"},
    {"id": "chandigarh", "name": "Chandigarh", "state": "CH", "lat": 30.733, "lon": 76.779, "type": "city"},
    {"id": "dehradun", "name": "Dehradun", "state": "UK", "lat": 30.317, "lon": 78.032, "type": "city"},
    {"id": "jaipur", "name": "Jaipur", "state": "RJ", "lat": 26.912, "lon": 75.787, "type": "city"},
    {"id": "agra", "name": "Agra", "state": "UP", "lat": 27.176, "lon": 78.008, "type": "city"},
    {"id": "lucknow", "name": "Lucknow", "state": "UP", "lat": 26.847, "lon": 80.947, "type": "city"},
    {"id": "meerut", "name": "Meerut", "state": "UP", "lat": 28.984, "lon": 77.706, "type": "agri"},
    {"id": "bhopal", "name": "Bhopal", "state": "MP", "lat": 23.260, "lon": 77.413, "type": "city"},
    {"id": "indore", "name": "Indore", "state": "MP", "lat": 22.720, "lon": 75.858, "type": "city"},
    {"id": "raipur", "name": "Raipur", "state": "CG", "lat": 21.251, "lon": 81.630, "type": "city"},
    {"id": "nagpur", "name": "Nagpur", "state": "MH", "lat": 21.146, "lon": 79.088, "type": "city"},
    {"id": "varanasi", "name": "Varanasi", "state": "UP", "lat": 25.318, "lon": 82.974, "type": "city"},
    {"id": "mumbai", "name": "Mumbai", "state": "MH", "lat": 19.076, "lon": 72.878, "type": "city"},
    {"id": "VABB", "name": "Mumbai Airport (BOM)", "state": "MH", "lat": 19.090, "lon": 72.866, "type": "airport"},
    {"id": "pune", "name": "Pune", "state": "MH", "lat": 18.520, "lon": 73.857, "type": "city"},
    {"id": "nashik", "name": "Nashik", "state": "MH", "lat": 19.998, "lon": 73.790, "type": "agri"},
    {"id": "ahmedabad", "name": "Ahmedabad", "state": "GJ", "lat": 23.023, "lon": 72.571, "type": "city"},
    {"id": "surat", "name": "Surat", "state": "GJ", "lat": 21.170, "lon": 72.831, "type": "city"},
    {"id": "goa", "name": "Panaji (Goa)", "state": "GA", "lat": 15.490, "lon": 73.828, "type": "city"},
    {"id": "bengaluru", "name": "Bengaluru", "state": "KA", "lat": 12.972, "lon": 77.595, "type": "city"},
    {"id": "VOBL", "name": "Bengaluru Airport (BLR)", "state": "KA", "lat": 13.199, "lon": 77.707, "type": "airport"},
    {"id": "chennai", "name": "Chennai", "state": "TN", "lat": 13.083, "lon": 80.271, "type": "city"},
    {"id": "VOMM", "name": "Chennai Airport (MAA)", "state": "TN", "lat": 12.990, "lon": 80.169, "type": "airport"},
    {"id": "hyderabad", "name": "Hyderabad", "state": "TS", "lat": 17.385, "lon": 78.487, "type": "city"},
    {"id": "coimbatore", "name": "Coimbatore", "state": "TN", "lat": 11.017, "lon": 76.956, "type": "city"},
    {"id": "madurai", "name": "Madurai", "state": "TN", "lat": 9.925, "lon": 78.120, "type": "city"},
    {"id": "kochi", "name": "Kochi", "state": "KL", "lat": 9.931, "lon": 76.267, "type": "city"},
    {"id": "mysuru", "name": "Mysuru", "state": "KA", "lat": 12.296, "lon": 76.639, "type": "agri"},
    {"id": "vijayawada", "name": "Vijayawada", "state": "AP", "lat": 16.506, "lon": 80.648, "type": "city"},
    {"id": "tirupati", "name": "Tirupati", "state": "AP", "lat": 13.628, "lon": 79.419, "type": "city"},
    {"id": "imphal", "name": "Imphal", "state": "MN", "lat": 24.817, "lon": 93.936, "type": "city"},
    {"id": "dibrugarh", "name": "Dibrugarh", "state": "AS", "lat": 27.472, "lon": 94.912, "type": "city"},
    {"id": "silchar", "name": "Silchar", "state": "AS", "lat": 24.833, "lon": 92.779, "type": "city"},
]